project:
  type: website
  output-dir: docs
  resources: 
    - "BingSiteAuth.xml"
    - "google37432af36185f94d.html"
    - "robots.txt"

website:
  title: "Random Thoughts"
  google-analytics: "G-D1ST9BH6HX" #"UA-20316028"
  favicon: images/favicon.ico
  twitter-card: true
  open-graph: true
  site-url: https://hassaanbinaslam.github.io/
  search: 
    location: navbar
    type: overlay

  comments:
    utterances:
      repo: hassaanbinaslam/myblog_utterances

  navbar:
    left:
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/hassaanbinaslam/
    right:
      - icon: github
        href: https://github.com/hassaanbinaslam/
      - icon: twitter
        href: https://twitter.com/hassaanbinaslam

format:
  html:
    code-line-numbers: true
    theme:
      - cosmo #spacelab # spacelab # simplex # litera # sandstone
      - custom.scss
    css: styles.css
