project:
  type: website
  output-dir: docs

website:
  title: "Random Thoughts"
  google-analytics: "UA-20316028"
  favicon: images/favicon.ico
  twitter-card: true
  open-graph: true

  comments:
    utterances:
      repo: hassaanbinaslam/myblog_utterances

  navbar:
    left:
      - about.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/hassaanbinaslam/
    right:
      - icon: github
        href: https://github.com/hassaanbinaslam/
      - icon: twitter
        href: https://twitter.com/hassaanbinaslam

format:
  html:
    theme:
      light: spacelab # spacelab # simplex # litera # sandstone
      dark: cyborg
    css: styles.css
